const supabaseClient=window.supabase.createClient('https://rcqvszklticaxnegcbaf.supabase.co','sb_publishable_PsScBfmvTJFqmSSF8ToNqg_EU1PgpHm');
let properties=[],filtered=[],current=0,currentUser='',saved=new Set(),drag=null,galleryIndex=0,galleryProperty=null;
const deck=document.querySelector('#deck'),empty=document.querySelector('#emptyState'),actions=document.querySelector('#actions'),progress=document.querySelector('#progress');
const euro=n=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const allAreasLabel='Alle Amsterdamse woningen';

function renderDeck(){
  deck.innerHTML='';
  filtered.slice(current,current+3).reverse().forEach((p)=>{
    const card=document.createElement('article');card.className='property-card';card.dataset.id=p.id;
    const position=filtered.indexOf(p)+1;
    const isTop=String(p.id)===String(filtered[current]?.id),mapQuery=encodeURIComponent(`${p.address}, Amsterdam`);
    const miniMap=isTop?`<div class="mini-map"><iframe src="https://www.google.com/maps?q=${mapQuery}&output=embed" title="Kaart van ${p.address}" loading="lazy" referrerpolicy="no-referrer-when-downgrade" tabindex="-1"></iframe><a class="map-link" href="https://www.google.com/maps/search/?api=1&query=${mapQuery}" target="_blank" rel="noopener noreferrer" aria-label="Open ${p.address} in Google Maps">Google Maps ↗</a></div>`:'';
    card.innerHTML=`<div class="swipe-stamp next">VOLGENDE</div><div class="swipe-stamp save">BEWAAR</div><div class="card-photo" tabindex="0" role="button" aria-label="Bekijk alle foto's van ${p.address}"><img src="${p.photos[0]}" alt="Interieur van ${p.address}"><span class="date-badge">${p.date}</span><span class="photo-count">▧ ${p.photos.length} foto's</span></div><div class="card-info"><span class="card-number">${String(position).padStart(2,'0')} / ${String(filtered.length).padStart(2,'0')}</span><h2>${p.address}</h2><p class="neighborhood">Amsterdam ${p.area}</p><p class="price">${euro(p.price)} <small>k.k.</small></p><div class="facts"><span class="fact"><strong>${p.size} m²</strong>Wonen</span><span class="fact"><strong>${p.beds}</strong>Slaapkamers</span><span class="fact"><strong>${p.energy}</strong>Energielabel</span></div>${miniMap}<span class="feature">${p.feature}</span><div class="property-links"><span class="details-link">Tik op de foto voor meer →</span>${p.url?`<a class="funda-link" href="${p.url}" target="_blank" rel="noopener noreferrer">Bekijk op Funda ↗</a>`:''}</div></div>`;
    deck.appendChild(card);
  });
  const done=current>=filtered.length;deck.hidden=done;empty.hidden=!done;actions.hidden=done;
  progress.innerHTML=filtered.map((_,i)=>`<span class="${i===current?'active':''}"></span>`).join('');
  bindTopCard();
}
function bindTopCard(){const card=deck.lastElementChild;if(!card)return;const p=properties.find(x=>String(x.id)===card.dataset.id);if(!p)return;const photo=card.querySelector('.card-photo');photo.onclick=()=>openGallery(p);photo.onkeydown=e=>{if(e.key==='Enter')openGallery(p)};card.onpointerdown=e=>{if(e.target.closest('.card-photo,.funda-link,.mini-map'))return;drag={x:e.clientX};card.setPointerCapture(e.pointerId)};card.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x;card.style.transition='none';card.style.transform=`translateX(${dx}px) rotate(${dx/30}deg)`;card.querySelector(dx>0?'.save':'.next').style.opacity=Math.min(Math.abs(dx)/100,1)};card.onpointerup=e=>{if(!drag)return;const dx=e.clientX-drag.x;drag=null;if(Math.abs(dx)>80)advance(dx>0,true);else{card.style.transition='';card.style.transform='';card.querySelectorAll('.swipe-stamp').forEach(x=>x.style.opacity=0)}}}
function advance(save=false,swiped=false){const card=deck.lastElementChild;if(!card)return;const p=filtered[current];if(save&&!currentUser){openAccount();return}if(save){saved.add(String(p.id));persistSaved();updateSaved()}const dir=save?1:-1;card.style.transition='transform .32s ease, opacity .32s';card.style.transform=`translateX(${dir*900}px) rotate(${dir*18}deg)`;card.style.opacity='0';setTimeout(()=>{current++;renderDeck()},280)}
function savedKey(){return `nieuw_saved_${currentUser.toLowerCase()}`}
function persistSaved(){if(currentUser)localStorage.setItem(savedKey(),JSON.stringify([...saved]))}
function loadSaved(){saved=new Set(currentUser?JSON.parse(localStorage.getItem(savedKey())||'[]').map(String):[]);updateSaved()}
function updateSaved(){document.querySelector('#savedCount').textContent=saved.size;document.querySelector('#accountLabel').textContent=currentUser?currentUser.split('@')[0]:'Inloggen';document.querySelector('#accountButton .avatar').textContent=currentUser?currentUser[0]:'↗'}

function relativeDate(value){if(!value)return'Nieuw';const days=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000));return days===0?'Vandaag':days===1?'Gisteren':`${days} dagen geleden`}
function normalizeProperty(p){return{id:p.funda_id,address:p.address,area:p.area||'Amsterdam',price:Number(p.price)||0,size:Number(p.size)||0,beds:Number(p.beds)||0,energy:p.energy||'—',date:relativeDate(p.published_at),feature:p.feature||'Nieuw op Funda',photos:Array.isArray(p.photos)&&p.photos.length?p.photos:['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1400&q=85'],url:p.url||''}}
async function loadLiveProperties(){const since=new Date(Date.now()-5*86400000).toISOString();const{data,error}=await supabaseClient.from('properties').select('*').gte('published_at',since).order('published_at',{ascending:false});properties=!error&&data?data.map(normalizeProperty):[];filtered=[...properties];current=0;setupFilters();renderDeck()}

function openAccount(){const m=document.querySelector('#accountModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>document.querySelector('#emailInput').focus(),50)}
function closeAccount(){document.querySelector('#accountModal').classList.remove('open');document.querySelector('#accountModal').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function renderSaved(){const list=document.querySelector('#savedList'),items=properties.filter(p=>saved.has(String(p.id)));document.querySelector('#userEmail').textContent=currentUser;document.querySelector('#userInitial').textContent=currentUser[0];list.innerHTML=items.length?items.map(p=>`<article class="saved-property"><img src="${p.photos[0]}" alt="${p.address}"><div class="saved-property-info"><button class="remove-saved" data-remove="${p.id}" aria-label="Verwijder ${p.address}">×</button><h3>${p.address}</h3><p>Amsterdam ${p.area} · ${p.size} m²</p><strong>${euro(p.price)} k.k.</strong></div></article>`).join(''):`<div class="no-saved"><span>♡</span><h3>Nog niets bewaard</h3><p>Tik op het hartje bij een woning die je mooi vindt.</p></div>`}
function openSaved(){if(!currentUser){openAccount();return}renderSaved();document.querySelector('#savedPanel').classList.add('open');document.querySelector('#savedPanel').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeSaved(){document.querySelector('#savedPanel').classList.remove('open');document.querySelector('#savedPanel').setAttribute('aria-hidden','true');document.body.style.overflow=''}

function setupFilters(){const neighborhoods=[...new Set(properties.map(p=>p.area).filter(a=>a&&a.toLowerCase()!=='amsterdam'))],areas=[allAreasLabel,...neighborhoods];document.querySelector('#areaDropdown').innerHTML=areas.map(a=>`<button data-area="${a}">${a}</button>`).join('');document.querySelectorAll('.filter-button').forEach(b=>b.onclick=e=>{e.stopPropagation();const dd=b.nextElementSibling;document.querySelectorAll('.dropdown').forEach(x=>x!==dd&&x.classList.remove('open'));dd.classList.toggle('open');b.setAttribute('aria-expanded',dd.classList.contains('open'))});document.onclick=()=>document.querySelectorAll('.dropdown').forEach(x=>x.classList.remove('open'));document.querySelector('#priceDropdown').onclick=e=>{e.stopPropagation();if(!e.target.dataset.price)return;document.querySelector('#priceLabel').textContent=e.target.textContent;document.querySelector('#priceFilter').dataset.value=e.target.dataset.price;applyFilters()};document.querySelector('#areaDropdown').onclick=e=>{e.stopPropagation();if(!e.target.dataset.area)return;document.querySelector('#areaLabel').textContent=e.target.dataset.area;document.querySelector('#areaFilter').dataset.value=e.target.dataset.area;applyFilters()}}
function applyFilters(){const pv=document.querySelector('#priceFilter').dataset.value||'all',av=document.querySelector('#areaFilter').dataset.value||allAreasLabel;filtered=properties.filter(p=>{const price=pv==='all'||(pv==='over'?p.price>=1000000:p.price<=+pv*1000);return price&&(av===allAreasLabel||p.area===av)});current=0;document.querySelectorAll('.dropdown').forEach(x=>x.classList.remove('open'));document.querySelectorAll('.filter-button').forEach(x=>x.setAttribute('aria-expanded','false'));renderDeck()}
function openGallery(p){galleryProperty=p;galleryIndex=0;updateGallery();const m=document.querySelector('#galleryModal');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function updateGallery(){document.querySelector('#galleryImage').src=galleryProperty.photos[galleryIndex];document.querySelector('#galleryAddress').textContent=galleryProperty.address;document.querySelector('#galleryCounter').textContent=`${galleryIndex+1} / ${galleryProperty.photos.length}`;const link=document.querySelector('#galleryFundaLink');link.href=galleryProperty.url||'#';link.hidden=!galleryProperty.url}
function closeGallery(){document.querySelector('#galleryModal').classList.remove('open');document.body.style.overflow=''}
document.querySelector('#passButton').onclick=()=>advance(false);document.querySelector('#likeButton').onclick=()=>advance(true);document.querySelector('#resetButton').onclick=()=>{current=0;renderDeck()};document.querySelector('#modalClose').onclick=closeGallery;document.querySelector('#galleryPrev').onclick=()=>{galleryIndex=(galleryIndex-1+galleryProperty.photos.length)%galleryProperty.photos.length;updateGallery()};document.querySelector('#galleryNext').onclick=()=>{galleryIndex=(galleryIndex+1)%galleryProperty.photos.length;updateGallery()};document.querySelector('#galleryModal').onclick=e=>{if(e.target.id==='galleryModal')closeGallery()};document.onkeydown=e=>{if(!galleryProperty)return;if(e.key==='Escape')closeGallery();if(e.key==='ArrowRight')document.querySelector('#galleryNext').click();if(e.key==='ArrowLeft')document.querySelector('#galleryPrev').click()};
document.querySelector('#accountButton').onclick=()=>currentUser?openSaved():openAccount();document.querySelector('#savedButton').onclick=openSaved;document.querySelector('[data-close-account]').onclick=closeAccount;document.querySelector('[data-close-saved]').onclick=closeSaved;document.querySelector('#accountModal').onclick=e=>{if(e.target.id==='accountModal')closeAccount()};document.querySelector('#savedPanel').onclick=e=>{if(e.target.id==='savedPanel')closeSaved()};
document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const email=document.querySelector('#emailInput').value.trim().toLowerCase(),password=document.querySelector('#passwordInput').value,feedback=document.querySelector('#formError');feedback.className='form-error';feedback.textContent='Even controleren…';const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(!error){currentUser=data.user.email;loadSaved();closeAccount();openSaved();e.target.reset();return}const {error:signUpError}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:'https://mijnvastgoed.github.io/'}});if(signUpError){feedback.textContent=signUpError.message;return}feedback.className='form-error success';feedback.textContent='Account gemaakt! Controleer je inbox en klik op de verificatielink.'};
document.querySelector('#forgotButton').onclick=async()=>{const email=document.querySelector('#emailInput').value.trim().toLowerCase(),feedback=document.querySelector('#formError');feedback.className='form-error';if(!email){feedback.textContent='Vul eerst je e-mailadres in.';return}const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:'https://mijnvastgoed.github.io/'});feedback.className=`form-error${error?'':' success'}`;feedback.textContent=error?error.message:'Je ontvangt zo een e-mail om je wachtwoord te wijzigen.'};
document.querySelector('#logoutButton').onclick=async()=>{await supabaseClient.auth.signOut();currentUser='';saved.clear();closeSaved();updateSaved()};document.querySelector('#savedList').onclick=e=>{const button=e.target.closest('[data-remove]');if(!button)return;saved.delete(String(button.dataset.remove));persistSaved();updateSaved();renderSaved()};
supabaseClient.auth.onAuthStateChange(async(event,session)=>{currentUser=session?.user?.email||'';loadSaved();if(event==='PASSWORD_RECOVERY'){const newPassword=window.prompt('Kies een nieuw wachtwoord (minimaal 6 tekens):');if(newPassword){const {error}=await supabaseClient.auth.updateUser({password:newPassword});window.alert(error?error.message:'Je wachtwoord is gewijzigd.')}}});
supabaseClient.auth.getSession().then(({data})=>{currentUser=data.session?.user?.email||'';loadSaved()});loadLiveProperties();
